In [1]:
import os
import pandas as pd
import numpy as np
import json

In [2]:
continents = ['North America', 'South America', 'Africa', 'Europe', 'Asia','Antarctica']

data = pd.read_csv(os.path.join("TemperatureFiles","GlobalLandTemperaturesByCountry.csv"))
data = data.dropna()

for continent in continents:
    data = data[data.Country != continent]

    
data.to_csv(os.path.join('Clean','icResults.csv'), index = False)
data

dt  AverageTemperature  AverageTemperatureUncertainty  \
0       1743-11-01               4.384                          2.294   
5       1744-04-01               1.530                          4.680   
6       1744-05-01               6.702                          1.789   
7       1744-06-01              11.609                          1.577   
8       1744-07-01              15.342                          1.410   
10      1744-09-01              11.702                          1.517   
11      1744-10-01               5.477                          1.862   
12      1744-11-01               3.407                          1.425   
13      1744-12-01              -2.181                          1.641   
14      1745-01-01              -3.850                          1.841   
15      1745-02-01              -6.575                          1.360   
16      1745-03-01              -4.195                          1.213   
17      1745-04-01              -0.966                          1.172   
74      1750-01-01               1.091                          1.119   
75      1750-02-01               0.809                          3.353   
76      1750-03-01               0.923                          4.716   
77      1750-04-01               3.943                          1.434   
78      1750-05-01               6.265                          1.339   
79      1750-06-01              12.408                          1.204   
80      1750-07-01              16.683                          1.184   
81      1750-08-01              17.076                          0.996   
82      1750-09-01              11.459                          1.881   
83      1750-10-01               2.627                          1.562   
85      1750-12-01              -4.058                          2.166   
86      1751-01-01              -3.408                          1.520   
87      1751-02-01              -8.393                          2.525   
88      1751-03-01              -0.122                          1.919   
89      1751-04-01               2.159                          0.922   
91      1751-06-01              10.688                          1.477   
92      1751-07-01              15.660                          0.966   
...            ...                 ...                            ...   
577431  2011-03-01              23.668                          0.183   
577432  2011-04-01              21.759                          0.319   
577433  2011-05-01              19.627                          0.398   
577434  2011-06-01              16.939                          0.599   
577435  2011-07-01              15.803                          0.447   
577436  2011-08-01              17.883                          0.328   
577437  2011-09-01              22.902                          0.612   
577438  2011-10-01              24.966                          0.441   
577439  2011-11-01              25.521                          0.318   
577440  2011-12-01              24.013                          0.356   
577441  2012-01-01              23.872                          0.247   
577442  2012-02-01              24.294                          0.305   
577443  2012-03-01              23.596                          0.354   
577444  2012-04-01              20.349                          0.462   
577445  2012-05-01              19.712                          0.312   
577446  2012-06-01              16.631                          0.277   
577447  2012-07-01              16.048                          0.783   
577448  2012-08-01              18.946                          1.127   
577449  2012-09-01              22.609                          0.643   
577450  2012-10-01              23.482                          0.574   
577451  2012-11-01              24.606                          0.532   
577452  2012-12-01              24.111                          0.846   
577453  2013-01-01              23.812                          1.218   
5

In [3]:
# Algoritmo

"""{"Mexico":
    {
        "1743": [1,2,3],
        "1744": [],
    },
    "USA":
    
}"""

countries_by_temp = dict()
dc = pd.read_csv(os.path.join("Clean","icResults.csv"))

for ind in dc.index:
    country =  dc['Country'][ind]
    if country not in countries_by_temp:
        countries_by_temp[country] = dict()
    year = dc['dt'][ind][:4]
    if year not in countries_by_temp[country]:
        countries_by_temp[country][year] = []
    countries_by_temp[country][year].append(dc['AverageTemperature'][ind])
    


In [4]:
#countries_by_temp

avg_per_year = {}

for country in countries_by_temp:
    avg_per_year[country] = {}
    
    for year in countries_by_temp[country]:
        
        avg = sum(countries_by_temp[country][year])/len(countries_by_temp[country][year])
        avg_per_year[country][year] = avg

In [5]:
dfTemp = pd.DataFrame.from_dict(avg_per_year)
dfTemp

Åland  Afghanistan    Albania    Algeria  American Samoa    Andorra  \
1743  4.384000          NaN   8.620000        NaN             NaN   7.556000   
1744  6.698500          NaN  14.061875        NaN             NaN  12.162750   
1745 -3.896500          NaN   5.588250        NaN             NaN   5.563500   
1750  6.293273          NaN  13.097909        NaN             NaN  11.759364   
1751  5.397375          NaN  13.573250        NaN             NaN  12.197000   
1752  1.625000          NaN   8.239833        NaN             NaN   7.418667   
1753  5.118333          NaN  12.557000        NaN             NaN  11.234500   
1754  5.118083          NaN  12.548167        NaN             NaN  11.116167   
1755  4.732833          NaN  12.322583        NaN             NaN  10.806667   
1756  5.160500          NaN  13.025917        NaN             NaN  11.097833   
1757  5.413833          NaN  12.730333        NaN             NaN  10.868250   
1758  4.074833          NaN  11.444333        NaN             NaN  10.144667   
1759  5.452083          NaN  12.492917        NaN             NaN  11.299750   
1760  4.322000          NaN  12.155000        NaN             NaN  11.082417   
1761  5.771583          NaN  12.876250        NaN             NaN  11.301917   
1762  5.217000          NaN  12.700250        NaN             NaN  11.143667   
1763  4.562500          NaN  12.024833        NaN             NaN  10.746333   
1764  5.562583          NaN  12.864167        NaN             NaN  11.237917   
1765  5.050583          NaN  12.737250        NaN             NaN  11.206167   
1766  5.894667          NaN  12.601417        NaN             NaN  11.059500   
1767  4.675417          NaN  12.169667        NaN             NaN  11.006583   
1768  4.544250          NaN  11.342333        NaN             NaN  10.644750   
1769  4.858083          NaN  12.395167        NaN             NaN  10.989917   
1770  4.985167          NaN  12.376417        NaN             NaN  10.828667   
1771  4.190167          NaN  12.370833        NaN             NaN  11.308917   
1772  4.704917          NaN  13.711417        NaN             NaN  12.267167   
1773  6.379333          NaN  12.693000        NaN             NaN  10.891750   
1774  4.530667          NaN  12.896333        NaN             NaN  11.323500   
1775  6.805750          NaN  13.221750        NaN             NaN  11.578667   
1776  5.652083          NaN  12.205917        NaN             NaN  11.163833   
...        ...          ...        ...        ...             ...        ...   
1984  6.234750    14.245833  12.640750  23.063083       26.879500  11.032750   
1985  3.467167    14.888750  12.948167  23.526250       26.949917  11.325417   
1986  5.000083    14.223167  13.056417  23.256667       26.980333  11.623500   
1987  3.718250    14.984000  12.996583  24.247750       26.898750  11.680250   
1988  6.001583    15.389000  13.044083  23.815667       27.089417  11.973917   
1989  7.249417    14.125750  12.803833  23.724333       26.752667  12.585083   
1990  7.221417    14.993333  13.468667  24.014417       27.156250  12.455583   
1991  6.433667    14.370750  12.338833  23.011083       27.171167  11.565417   
1992  6.782333    14.056083  13.084667  22.767000       27.072000  11.498417   
1993  5.906750    14.439250  13.122583  23.450833       26.816417  11.432167   
1994  5.899500    14.754750  14.099667  23.642083       26.986333  12.632250   
1995  6.200167    14.859167  12.782083  23.722500       27.268667  12.376417   
1996  5.236333    14.426000  12.736500  23.734333       27.112667  11.741417   
1997  6.674250    14.904000  12.900917  23.955167       26.955750  12.896167   
1998  5.841250    15.132500  13.311250  23.920583       27.424833  12.118750   
1999  6.764000    15.388750  13.653750  24.299417       27.067167  12.178667   
2000  7.283333    15.497833  13.746583  24.032250       27.219833  12.311917   
2001  6.401500    15.778083  13.690417  24.724417       27.227583  12.216083   
2002  6.8

In [6]:
startYear = dfTemp.dropna()
startYear

Åland  Afghanistan    Albania    Algeria  American Samoa    Andorra  \
1948  6.045500    14.335250  12.753917  23.071333       26.680417  11.935583   
1949  7.081083    13.350083  12.518250  23.188167       26.851000  12.317917   
1950  5.957917    13.043500  13.812833  22.781833       26.520083  11.812000   
1951  5.820583    13.967750  13.569833  23.321667       26.689667  10.972917   
1952  4.795000    14.175417  13.573917  23.185417       27.063750  11.660833   
1953  6.746917    14.650750  12.586333  22.869417       26.949250  11.471000   
1954  5.551750    13.691333  12.450083  22.652417       26.866083  10.902000   
1955  4.887417    14.642583  13.148083  24.004833       26.710750  11.727500   
1956  4.045583    14.191083  12.172333  22.611333       26.466833  10.363250   
1957  5.594583    12.777167  13.078417  22.620250       26.762917  11.144083   
1958  4.637583    14.716750  13.194500  23.544917       26.918083  11.501833   
1959  6.630917    14.152583  12.405583  23.333667       26.791833  11.720417   
1960  5.548750    13.985417  13.335083  23.504083       26.765500  11.214000   
1961  6.833083    14.064917  13.316750  23.390333       26.617167  12.261500   
1962  4.790500    13.768667  13.068750  23.182417       26.627667  11.079333   
1963  4.887750    15.033417  13.085833  23.317833       26.857667  10.636167   
1964  5.586417    13.084917  12.515333  23.147500       26.595667  11.541083   
1965  4.880250    14.101833  12.378417  22.973750       26.381250  11.025917   
1966  4.298333    14.343000  13.204583  23.301333       26.822167  11.584750   
1967  5.878000    13.663250  12.621750  22.861667       26.420417  11.606917   
1968  5.172833    13.762333  12.869583  23.185917       26.480833  11.436500   
1969  4.918417    13.805083  12.802917  23.458250       26.936583  10.884833   
1970  4.442833    14.783083  12.839667  23.322833       26.760667  11.376583   
1971  5.623750    14.823500  12.534417  22.672250       26.402250  11.192167   
1972  6.358333    12.547167  12.608250  22.698167       26.812333  10.741000   
1973  6.198083    14.235500  12.486667  22.886167       27.138250  11.176583   
1974  6.766917    13.316750  12.559833  22.541000       26.591250  11.077333   
1975  7.237833    13.548083  12.568417  22.716417       26.773167  11.247750   
1976  4.832917    13.708583  12.036250  22.356750       26.721083  11.304500   
1977  5.159250    14.805417  13.223250  23.546083       26.786833  11.134333   
...        ...          ...        ...        ...             ...        ...   
1984  6.234750    14.245833  12.640750  23.063083       26.879500  11.032750   
1985  3.467167    14.888750  12.948167  23.526250       26.949917  11.325417   
1986  5.000083    14.223167  13.056417  23.256667       26.980333  11.623500   
1987  3.718250    14.984000  12.996583  24.247750       26.898750  11.680250   
1988  6.001583    15.389000  13.044083  23.815667       27.089417  11.973917   
1989  7.249417    14.125750  12.803833  23.724333       26.752667  12.585083   
1990  7.221417    14.993333  13.468667  24.014417       27.156250  12.455583   
1991  6.433667    14.370750  12.338833  23.011083       27.171167  11.565417   
1992  6.782333    14.056083  13.084667  22.767000       27.072000  11.498417   
1993  5.906750    14.439250  13.122583  23.450833       26.816417  11.432167   
1994  5.899500    14.754750  14.099667  23.642083       26.986333  12.632250   
1995  6.200167    14.859167  12.782083  23.722500       27.268667  12.376417   
1996  5.236333    14.426000  12.736500  23.734333       27.112667  11.741417   
1997  6.674250    14.904000  12.900917  23.955167       26.955750  12.896167   
1998  5.841250    15.132500  13.311250  23.920583       27.424833  12.118750   
1999  6.764000    15.388750  13.653750  24.299417       27.067167  12.178667   
2000  7.283333    15.497833  13.746583  24.032250       27.219833  12.311917   
2001  6.401500    15.778083  13.690417  24.724417       27.227583  12.216083   
2002  6.8

In [7]:
"""

<0 - Muy Frio
0 < 10 - Frio
10 < 20 - Templado
20 < 25 - Calido
25 <   - Muy Calido 


http://www.met.igp.gob.pe/clima/clasif.html
"""

matrix_countries = {}

for country in countries_by_temp:
    matrix_countries[country] = np.zeros(shape=(5,5))

#print(matrix_countries["Mexico"])

In [8]:
def get_temp(temp):
    if temp < 0:
        return 0
    elif temp < 10:
        return 1
    elif temp < 20:
        return 2
    elif temp < 25:
        return 3
    else:
        return 4

def add_counter(country, prev, current):
    row = get_temp(prev)
    col = get_temp(current)
    matrix_countries[country][row][col] += 1

In [9]:
#import math

for (columnName, columnData) in dfTemp.iteritems():
    noNanData = []
    for number in columnData:
        if number == number:
            noNanData.append(number)
    for i in range(len(noNanData)-2):
        prev = noNanData[i]
        current = noNanData[i+1]
        add_counter(columnName, prev, current)
        
print(matrix_countries["Chile"])

[[  0.   0.   0.   0.   0.]
 [  0. 130.  12.   0.   0.]
 [  0.  11.   4.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]]


In [10]:
#[2,3,4]

#{"":[[[],[]],[]]}
#{"":{"matrix":, "states":}}

def reduce_matrix(matrix_country):
    states = []
    for i in range(5):
        for j in range(5):
            if matrix_country[i][j] != 0:
                states.append(i)
                break
    #print(states)
    reduced_matrix = np.zeros(shape=(len(states),len(states)))
    row = 0
    for i in states:
        column = 0
        for j in states:
            reduced_matrix[row][column] = matrix_country[i][j]
            column += 1
        row += 1
    #print(reduced_matrix)
    return [reduced_matrix, states]
print(reduce_matrix(matrix_countries["Chile"]))

[array([[130.,  12.],
       [ 11.,   4.]]), [1, 2]]


In [11]:
reduced_matrices = {}

for country_matrix in matrix_countries:
    reduced_matrices[country_matrix] = {}
    temp = reduce_matrix(matrix_countries[country_matrix])
    reduced_matrices[country_matrix]["Matrix"] = temp[0]
    reduced_matrices[country_matrix]["States"] = temp[1]
    
print(reduced_matrices["Chile"])



{'Matrix': array([[130.,  12.],
       [ 11.,   4.]]), 'States': [1, 2]}


In [12]:
def estocastica(matrix):
    for i in range(len(matrix)):
        add = sum(matrix[i])
        for j in range(len(matrix[i])):
            matrix[i][j] = matrix[i][j]/add      

In [13]:
for reduced_matrix in reduced_matrices:
    estocastica(reduced_matrices[reduced_matrix]["Matrix"])

In [14]:
for reduced_matrix in reduced_matrices:
    reduced_matrices[reduced_matrix]["Matrix"] = reduced_matrices[reduced_matrix]["Matrix"].tolist()

In [15]:
with open(os.path.join("Clean","markov.json"), 'w') as file:
    json.dump(reduced_matrices, file)

In [17]:
print(reduced_matrices["Brazil"])

{'Matrix': [[0.8787878787878788, 0.12121212121212122], [0.3191489361702128, 0.6808510638297872]], 'States': [3, 4]}
