# Métodos Cuantitativos y de Simulación
## Proyecto Final  
Proyecto para simular el comportamiento de la temperatura superficial de los países.  

- El data set utiliza temperaturas superficiales de la tierra de varios países, contiene datos desde 1743. [Dataset](https://www.kaggle.com/berkeleyearth/climate-change-earth-surface-temperature-data)

In [76]:
import os
import pandas as pd
import numpy as np
import json

## Limpieza de datos

- Eliminar filas vacias
- Sacar continentes

In [77]:
continents = ['North America', 'South America', 'Africa', 'Europe', 'Asia','Antarctica']

data = pd.read_csv(os.path.join("TemperatureFiles","GlobalLandTemperaturesByCountry.csv"))
data = data.dropna()

for continent in continents:
    data = data[data.Country != continent]

In [78]:
# 1743

year = 1948

data['dt'] = data['dt'].astype(str).str[:4]

data = data[data['dt'].astype(int) >= year]

data.to_csv(os.path.join('Clean','icResults.csv'), index = False)

data

dt  AverageTemperature  AverageTemperatureUncertainty   Country
2450    1948              -4.641                          0.867     Åland
2451    1948              -3.767                          0.744     Åland
2452    1948               0.743                          0.693     Åland
2453    1948               3.959                          0.599     Åland
2454    1948               8.036                          0.501     Åland
2455    1948              12.181                          0.302     Åland
2456    1948              16.355                          0.466     Åland
2457    1948              14.849                          0.282     Åland
2458    1948              11.981                          0.149     Åland
2459    1948               6.246                          0.155     Åland
2460    1948               3.094                          0.403     Åland
2461    1948               3.510                          0.801     Åland
2462    1949               1.045                          0.622     Åland
2463    1949               1.166                          0.499     Åland
2464    1949              -1.079                          0.367     Åland
2465    1949               3.230                          0.361     Åland
2466    1949               9.276                          0.415     Åland
2467    1949              11.146                          0.409     Åland
2468    1949              15.661                          0.287     Åland
2469    1949              14.612                          0.275     Åland
2470    1949              14.838                          0.164     Åland
2471    1949               8.003                          0.280     Åland
2472    1949               4.978                          0.372     Åland
2473    1949               2.097                          0.457     Åland
2474    1950              -5.611                          0.816     Åland
2475    1950              -1.804                          0.305     Åland
2476    1950               0.090                          0.439     Åland
2477    1950               3.630                          0.342     Åland
2478    1950               8.106                          0.239     Åland
2479    1950              12.783                          0.235     Åland
...      ...                 ...                            ...       ...
577431  2011              23.668                          0.183  Zimbabwe
577432  2011              21.759                          0.319  Zimbabwe
577433  2011              19.627                          0.398  Zimbabwe
577434  2011              16.939                          0.599  Zimbabwe
577435  2011              15.803                          0.447  Zimbabwe
577436  2011              17.883                          0.328  Zimbabwe
577437  2011              22.902                          0.612  Zimbabwe
577438  2011              24.966                          0.441  Zimbabwe
577439  2011              25.521                          0.318  Zimbabwe
577440  2011              24.013                          0.356  Zimbabwe
577441  2012              23.872                          0.247  Zimbabwe
577442  2012              24.294                          0.305  Zimbabwe
577443  2012              23.596                          0.354  Zimbabwe
577444  2012              20.349                          0.462  Zimbabwe
577445  2012              19.712                          0.312  Zimbabwe
577446  2012              16.631                          0.277  Zimbabwe
577447  2012              16.048                          0.783  Zimbabwe
577448  2012              18.946                          1.127  Zimbabwe
577449  2012              22.609                          0.643  Zimbabwe
577450  2012              23.482                          0.574  Zimbabwe
577451  2012              24.606                          0.532  Zimbabwe
577452  2012              24.111                          0.846  Zimbabwe
577453  2013  

## Acomodar datos por país

- Se guardan las temperaturas por año de cada país

In [79]:
"""{"Mexico":
    {
        "1743": [3.2,3.1,3.0],
        "1744": [],
    },
    "USA":
    
}"""

countries_by_temp = dict()
dc = pd.read_csv(os.path.join("Clean","icResults.csv"))

for ind in dc.index:
    country =  dc['Country'][ind]
    if country not in countries_by_temp:
        countries_by_temp[country] = dict()
    year = dc['dt'][ind]
    if year not in countries_by_temp[country]:
        countries_by_temp[country][year] = []
    countries_by_temp[country][year].append(dc['AverageTemperature'][ind])
    


## Sacar promedio por año
- Se saca la temperatura promedio de cada año de cada país

In [80]:
#countries_by_temp

avg_per_year = {}

for country in countries_by_temp:
    avg_per_year[country] = {}
    
    for year in countries_by_temp[country]:
        
        avg = sum(countries_by_temp[country][year])/len(countries_by_temp[country][year])
        avg_per_year[country][year] = avg

In [81]:
dfTemp = pd.DataFrame.from_dict(avg_per_year)
dfTemp

Åland  Afghanistan    Albania    Algeria  American Samoa    Andorra  \
1948  6.045500    14.335250  12.753917  23.071333       26.680417  11.935583   
1949  7.081083    13.350083  12.518250  23.188167       26.851000  12.317917   
1950  5.957917    13.043500  13.812833  22.781833       26.520083  11.812000   
1951  5.820583    13.967750  13.569833  23.321667       26.689667  10.972917   
1952  4.795000    14.175417  13.573917  23.185417       27.063750  11.660833   
1953  6.746917    14.650750  12.586333  22.869417       26.949250  11.471000   
1954  5.551750    13.691333  12.450083  22.652417       26.866083  10.902000   
1955  4.887417    14.642583  13.148083  24.004833       26.710750  11.727500   
1956  4.045583    14.191083  12.172333  22.611333       26.466833  10.363250   
1957  5.594583    12.777167  13.078417  22.620250       26.762917  11.144083   
1958  4.637583    14.716750  13.194500  23.544917       26.918083  11.501833   
1959  6.630917    14.152583  12.405583  23.333667       26.791833  11.720417   
1960  5.548750    13.985417  13.335083  23.504083       26.765500  11.214000   
1961  6.833083    14.064917  13.316750  23.390333       26.617167  12.261500   
1962  4.790500    13.768667  13.068750  23.182417       26.627667  11.079333   
1963  4.887750    15.033417  13.085833  23.317833       26.857667  10.636167   
1964  5.586417    13.084917  12.515333  23.147500       26.595667  11.541083   
1965  4.880250    14.101833  12.378417  22.973750       26.381250  11.025917   
1966  4.298333    14.343000  13.204583  23.301333       26.822167  11.584750   
1967  5.878000    13.663250  12.621750  22.861667       26.420417  11.606917   
1968  5.172833    13.762333  12.869583  23.185917       26.480833  11.436500   
1969  4.918417    13.805083  12.802917  23.458250       26.936583  10.884833   
1970  4.442833    14.783083  12.839667  23.322833       26.760667  11.376583   
1971  5.623750    14.823500  12.534417  22.672250       26.402250  11.192167   
1972  6.358333    12.547167  12.608250  22.698167       26.812333  10.741000   
1973  6.198083    14.235500  12.486667  22.886167       27.138250  11.176583   
1974  6.766917    13.316750  12.559833  22.541000       26.591250  11.077333   
1975  7.237833    13.548083  12.568417  22.716417       26.773167  11.247750   
1976  4.832917    13.708583  12.036250  22.356750       26.721083  11.304500   
1977  5.159250    14.805417  13.223250  23.546083       26.786833  11.134333   
...        ...          ...        ...        ...             ...        ...   
1984  6.234750    14.245833  12.640750  23.063083       26.879500  11.032750   
1985  3.467167    14.888750  12.948167  23.526250       26.949917  11.325417   
1986  5.000083    14.223167  13.056417  23.256667       26.980333  11.623500   
1987  3.718250    14.984000  12.996583  24.247750       26.898750  11.680250   
1988  6.001583    15.389000  13.044083  23.815667       27.089417  11.973917   
1989  7.249417    14.125750  12.803833  23.724333       26.752667  12.585083   
1990  7.221417    14.993333  13.468667  24.014417       27.156250  12.455583   
1991  6.433667    14.370750  12.338833  23.011083       27.171167  11.565417   
1992  6.782333    14.056083  13.084667  22.767000       27.072000  11.498417   
1993  5.906750    14.439250  13.122583  23.450833       26.816417  11.432167   
1994  5.899500    14.754750  14.099667  23.642083       26.986333  12.632250   
1995  6.200167    14.859167  12.782083  23.722500       27.268667  12.376417   
1996  5.236333    14.426000  12.736500  23.734333       27.112667  11.741417   
1997  6.674250    14.904000  12.900917  23.955167       26.955750  12.896167   
1998  5.841250    15.132500  13.311250  23.920583       27.424833  12.118750   
1999  6.764000    15.388750  13.653750  24.299417       27.067167  12.178667   
2000  7.283333    15.497833  13.746583  24.032250       27.219833  12.311917   
2001  6.401500    15.778083  13.690417  24.724417       27.227583  12.216083   
2002  6.8

In [82]:
startYear = dfTemp.dropna()
startYear

Åland  Afghanistan    Albania    Algeria  American Samoa    Andorra  \
1948  6.045500    14.335250  12.753917  23.071333       26.680417  11.935583   
1949  7.081083    13.350083  12.518250  23.188167       26.851000  12.317917   
1950  5.957917    13.043500  13.812833  22.781833       26.520083  11.812000   
1951  5.820583    13.967750  13.569833  23.321667       26.689667  10.972917   
1952  4.795000    14.175417  13.573917  23.185417       27.063750  11.660833   
1953  6.746917    14.650750  12.586333  22.869417       26.949250  11.471000   
1954  5.551750    13.691333  12.450083  22.652417       26.866083  10.902000   
1955  4.887417    14.642583  13.148083  24.004833       26.710750  11.727500   
1956  4.045583    14.191083  12.172333  22.611333       26.466833  10.363250   
1957  5.594583    12.777167  13.078417  22.620250       26.762917  11.144083   
1958  4.637583    14.716750  13.194500  23.544917       26.918083  11.501833   
1959  6.630917    14.152583  12.405583  23.333667       26.791833  11.720417   
1960  5.548750    13.985417  13.335083  23.504083       26.765500  11.214000   
1961  6.833083    14.064917  13.316750  23.390333       26.617167  12.261500   
1962  4.790500    13.768667  13.068750  23.182417       26.627667  11.079333   
1963  4.887750    15.033417  13.085833  23.317833       26.857667  10.636167   
1964  5.586417    13.084917  12.515333  23.147500       26.595667  11.541083   
1965  4.880250    14.101833  12.378417  22.973750       26.381250  11.025917   
1966  4.298333    14.343000  13.204583  23.301333       26.822167  11.584750   
1967  5.878000    13.663250  12.621750  22.861667       26.420417  11.606917   
1968  5.172833    13.762333  12.869583  23.185917       26.480833  11.436500   
1969  4.918417    13.805083  12.802917  23.458250       26.936583  10.884833   
1970  4.442833    14.783083  12.839667  23.322833       26.760667  11.376583   
1971  5.623750    14.823500  12.534417  22.672250       26.402250  11.192167   
1972  6.358333    12.547167  12.608250  22.698167       26.812333  10.741000   
1973  6.198083    14.235500  12.486667  22.886167       27.138250  11.176583   
1974  6.766917    13.316750  12.559833  22.541000       26.591250  11.077333   
1975  7.237833    13.548083  12.568417  22.716417       26.773167  11.247750   
1976  4.832917    13.708583  12.036250  22.356750       26.721083  11.304500   
1977  5.159250    14.805417  13.223250  23.546083       26.786833  11.134333   
...        ...          ...        ...        ...             ...        ...   
1984  6.234750    14.245833  12.640750  23.063083       26.879500  11.032750   
1985  3.467167    14.888750  12.948167  23.526250       26.949917  11.325417   
1986  5.000083    14.223167  13.056417  23.256667       26.980333  11.623500   
1987  3.718250    14.984000  12.996583  24.247750       26.898750  11.680250   
1988  6.001583    15.389000  13.044083  23.815667       27.089417  11.973917   
1989  7.249417    14.125750  12.803833  23.724333       26.752667  12.585083   
1990  7.221417    14.993333  13.468667  24.014417       27.156250  12.455583   
1991  6.433667    14.370750  12.338833  23.011083       27.171167  11.565417   
1992  6.782333    14.056083  13.084667  22.767000       27.072000  11.498417   
1993  5.906750    14.439250  13.122583  23.450833       26.816417  11.432167   
1994  5.899500    14.754750  14.099667  23.642083       26.986333  12.632250   
1995  6.200167    14.859167  12.782083  23.722500       27.268667  12.376417   
1996  5.236333    14.426000  12.736500  23.734333       27.112667  11.741417   
1997  6.674250    14.904000  12.900917  23.955167       26.955750  12.896167   
1998  5.841250    15.132500  13.311250  23.920583       27.424833  12.118750   
1999  6.764000    15.388750  13.653750  24.299417       27.067167  12.178667   
2000  7.283333    15.497833  13.746583  24.032250       27.219833  12.311917   
2001  6.401500    15.778083  13.690417  24.724417       27.227583  12.216083   
2002  6.8

## Clasificación de temperaturas
### Hay 5 temperaturas:
- <b>Muy frío</b>: abajo de 0 grados
- <b>Frío</b>: entre 0 y 10 grados
- <b>Templado</b>: entre 10 y 20 grados
- <b>Cálido</b>: entre 20 y 25 grados
- <b>Muy Cálido</b>: arriba de 25 grados  

## Creación de matrices

- Las matrices cuentan las transiciones de estado de cada país

In [83]:
"""

<0 - Muy Frio
0 < 10 - Frio
10 < 20 - Templado
20 < 25 - Calido
25 <   - Muy Calido 


http://www.met.igp.gob.pe/clima/clasif.html
"""

matrix_countries = {}

for country in countries_by_temp:
    matrix_countries[country] = np.zeros(shape=(5,5))

In [84]:
def get_temp(temp):
    if temp < 0:
        return 0
    elif temp < 10:
        return 1
    elif temp < 20:
        return 2
    elif temp < 25:
        return 3
    else:
        return 4

def add_counter(country, prev, current):
    row = get_temp(prev)
    col = get_temp(current)
    matrix_countries[country][row][col] += 1

In [85]:
for (columnName, columnData) in dfTemp.iteritems():
    noNanData = []
    for number in columnData:
        if number == number:
            noNanData.append(number)
    for i in range(len(noNanData)-2):
        prev = noNanData[i]
        current = noNanData[i+1]
        add_counter(columnName, prev, current)

In [86]:
print(matrix_countries["Chile"])

[[ 0.  0.  0.  0.  0.]
 [ 0. 39. 11.  0.  0.]
 [ 0. 10.  4.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


## Matrices estocásticas
#### Para generar las matrices estocásticas se realizan dos pasos

- Se reducen a matrices cuadradas sin filas y columnas llenas de 0s
- Se convierten los contadores a probabilidades

In [87]:
#[2,3,4]

#{"":[[[],[]],[]]}
#{"":{"matrix":, "states":}}

def reduce_matrix(matrix_country):
    states = []
    for i in range(5):
        for j in range(5):
            if matrix_country[i][j] != 0:
                states.append(i)
                break
    #print(states)
    reduced_matrix = np.zeros(shape=(len(states),len(states)))
    row = 0
    for i in states:
        column = 0
        for j in states:
            reduced_matrix[row][column] = matrix_country[i][j]
            column += 1
        row += 1
    return [reduced_matrix, states]

In [88]:
reduced_matrices = {}

for country_matrix in matrix_countries:
    reduced_matrices[country_matrix] = {}
    temp = reduce_matrix(matrix_countries[country_matrix])
    reduced_matrices[country_matrix]["Matrix"] = temp[0]
    reduced_matrices[country_matrix]["States"] = temp[1]

In [89]:
print(reduced_matrices["Chile"])

{'Matrix': array([[39., 11.],
       [10.,  4.]]), 'States': [1, 2]}


In [90]:
def estocastica(matrix):
    for i in range(len(matrix)):
        add = sum(matrix[i])
        for j in range(len(matrix[i])):
            matrix[i][j] = matrix[i][j]/add      

In [91]:
for reduced_matrix in reduced_matrices:
    estocastica(reduced_matrices[reduced_matrix]["Matrix"])

In [92]:
for reduced_matrix in reduced_matrices:
    reduced_matrices[reduced_matrix]["Matrix"] = reduced_matrices[reduced_matrix]["Matrix"].tolist()

In [93]:
with open(os.path.join("Clean","markov.json"), 'w') as file:
    json.dump(reduced_matrices, file)

In [95]:
print(reduced_matrices["Egypt"])

{'Matrix': [[0.9841269841269841, 0.015873015873015872], [1.0, 0.0]], 'States': [3, 4]}
